### ISSUE TITLE
怎么样才能识别 image-width 这个函数？目前是原样编译

### ISSUE THREAD

**Issue by DeyuanTan** [xiangshouding/fis-parser-sass-by-ruby#2]
RT

**Comment by oxUnd** [comment]
装最新版的 sass

**Comment by DeyuanTan** [comment]
最新版也不行。直接用compass watch是能够正常使用compass helper的函数的。

**Comment by oxUnd** [comment]
不会吧，我是调用 sass 来编译的；

**Comment by DeyuanTan** [comment]
image-width是compass helper吧，不是sass内置的吧？已经选用 fis-parser-node-sass 解决问题了。
https://github.com/fex-team/fis3/issues/270#issuecomment-153944103
